Repository Coders-Evoke-Community/CodersEvoke_website, pull requests merged in 2021-07, with the labels that each got.

#55 Designed home page
  assets/css/style.css
  assets/images/about-us.jpg
  assets/images/home.svg
  index.html
Labels: 🟨 Level2

#54 Linked contributer.md to readme file
  README.md
Labels: 🟪 Level0

#59 Bottom-to-top-scroll-button-added
  assets/css/style.css
  index.html
Labels: 🟩 Level1

#61 Added HoverEffect
  assets/css/style.css
  index.html
Labels: 🟩 Level1

#64 Add 404 Page
  404 Page/404style.css
  404Page.html
Labels: DCP21, 🟩 Level1

#66 Added Footer
  assets/css/style.css
  index.html
Labels: DCP21, 🟨 Level2

#76 Added UI Designs
  ui designs/About Us.png
  ui designs/Home Page.png
  ui designs/Our Events.png
Labels: 🟩 Level1

#101 Added logo in navbar
  assets/css/style.css
  assets/images/circle-cropped.png
  index.html
Labels: DCP21, 🟨 Level2

#100 Added Admin Section
  README.md
Labels: DCP21, 🟧 Level3

#106 Added Mentor Section and Centered the Admin Section
  README.md
Labels: DCP21, 🟩 Level1

#109 Events Page update
  assets/css/event.css
  assets/css/style.css
  contact.html
  events.html
  index.html
Labels: DCP21

#110 Fixed Horizontal Scrollbar
  assets/css/style.css
Labels: DCP21, 🟩 Level1

#120 Added Contact Form Backend
  assets/css/contact.css
  contact.html
  js/contact.js
Labels: DCP21, 🟧 Level3

#123 Added Logo on Event Page
  events.html
Labels: DCP21, 🟩 Level1

#130 Fixed logo hover effect
  assets/css/event.css
  assets/css/style.css
  events.html
  index.html
Labels: DCP21, 🟩 Level1

#131 Opportunity
  assets/css/opportunity.css
  assets/images/background.jpg.jpg
  assets/images/innovation.jpg
  assets/images/leader.jpg
  assets/images/love.jpg
  assets/images/work hard.jpg
  home.html
Labels: DCP21, 🟨 Level2

#128 fix: stretchy image
  contact.html
Labels: DCP21, 🟪 Level0

#136 Adding responsiveness
  assets/css/contact.css
  assets/css/style.css
  contact.html
  events.html
  index.html
Labels: DCP21, 🟧 Level3

#108 Added Responsiveness
  assets/css/contact.css
  assets/css/style.css
  contact.html
  events.html
  index.html
Labels: DCP21, 🟧 Level3

#141 fix: Issue in contact us page
  assets/css/contact.css
  contact.html
Labels: DCP21, 🟩 Level1

#143 Enhanced hover effect on cards present in event page
  assets/css/style.css
Labels: DCP21, 🟪 Level0

#154 Given footers to events & contact
  contact.html
  events.html
Labels: DCP21, 🟩 Level1

#159 About page footer
  about.html
Labels: 🟩 Level1

#161 changes in the home page and contact page
  assets/css/contact.css
  assets/css/style.css
  contact.html
Labels: DCP21, 🟨 Level2
